version: '3.9'

services:
  app:
    image: node:18-alpine
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env # Reference the .env file
    networks:
      - docker-network
  
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge



  