version: '3.9'

services:
  app:
    image: node:18-alpine
    container_name: app
    command: npm start
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - docker-network
    volumes:
      - ./:/app
  
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 5432:5432
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

  